# Generated by Django 5.2.6 on 2025-10-14 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_tensor_img',
            new_name='location_tensors_imgs',
        ),
    ]
