# Generated by Django 5.2.6 on 2025-11-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_rename_location_tensor_img_location_location_tensors_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='connections',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='popularity',
            field=models.FloatField(null=True),
        ),
    ]
